ISUCON13_MYSQL_DIALCONFIG_NET="tcp"
ISUCON13_MYSQL_DIALCONFIG_ADDRESS="__ISU2_IP__"
ISUCON13_MYSQL_DIALCONFIG_PORT="3306"
ISUCON13_MYSQL_DIALCONFIG_USER="isucon"
ISUCON13_MYSQL_DIALCONFIG_DATABASE="isupipe"
ISUCON13_MYSQL_DIALCONFIG_PARSETIME="true"
ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="__ISU3_IP__"
ISUCON13_POWERDNS_DISABLED="false"
# 配信者サブドメイン（初期ユーザー含む）の A レコードは名前のハッシュでこの中から。pipe 等は上（isu3）
ISUCON13_DNS_USER_ADDRESS="__ISU2_IP__,__ISU3_IP__"
# GC の頻度を下げる（ヒープは数百 MB、メモリは 4GB）
GOGC=400
# pipe の A レコード（問い合わせごとにラウンドロビン、TTL 1 秒。TLS ハンドシェイクを 3 台に分散）
ISUCON13_DNS_PIPE_ADDRESS="__ISU3_IP__,__ISU1_IP__,__ISU3_IP__,__ISU2_IP__"
